# Build Docker.
FROM alpine AS build

RUN apk add --no-cache build-base curl gcompat git

RUN if [ "$(apk --print-arch)" = "x86_64" ]; then \
    curl -fsSL \
      -o /usr/local/bin/nimby \
https://github.com/treeform/nimby/releases/download/0.1.26/nimby-Linux-X64; \
  elif [ "$(apk --print-arch)" = "aarch64" ]; then \
    curl -fsSL \
      -o /usr/local/bin/nimby \
https://github.com/treeform/nimby/releases/download/0.1.26/nimby-Linux-ARM64; \
  else \
    echo "unsupported arch: $(apk --print-arch)" && exit 1; \
  fi && \
  chmod +x /usr/local/bin/nimby && \
  nimby use 2.2.4

ENV PATH="/root/.nimby/nim/bin:$PATH"

WORKDIR /workspace/bitworld
COPY nimby.lock .
RUN nimby --global sync nimby.lock && \
  cat nim.cfg >> /root/.nimby/nim/config/nim.cfg

COPY . .
WORKDIR /workspace/bitworld/among_them/players
RUN nim c \
  -d:release \
  -d:botHeadless \
  --nimcache:/tmp/bitworld-nimcache \
  --out:/tmp/evidencebot_v2 \
  evidencebot_v2.nim

# Run Docker.
FROM alpine

WORKDIR /workspace/bitworld
COPY --from=build \
  /tmp/evidencebot_v2 \
  /bin/evidencebot_v2
COPY --from=build /workspace/bitworld/among_them/*.json ./among_them/
COPY --from=build /workspace/bitworld/among_them/*.aseprite ./among_them/
COPY --from=build /workspace/bitworld/among_them/*.png ./among_them/
COPY --from=build /workspace/bitworld/clients/data ./clients/data

WORKDIR /workspace/bitworld/among_them/players
CMD ["/bin/evidencebot_v2", "--address:host.docker.internal", "--port:8080"]
