"""Digest invariant for checked-in baked perception assets (PLAN R3).

Every ``.npz`` file generated by ``generate_baked.py`` has its sha256
recorded in ``baked_manifest.json``. :func:`verify_all` is invoked at
package import (see ``__init__.py``) so a drifted artifact fails loudly
the first time anything from the package is touched.

The canonical recovery is to re-run ``generate_baked.py``.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

_DATA_DIR = Path(__file__).resolve().parent
_MANIFEST_PATH = _DATA_DIR / "baked_manifest.json"


class BakeManifestMismatch(RuntimeError):
    """Raised when a checked-in baked asset disagrees with the recorded digest."""


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def load_manifest(manifest_path: Path | None = None) -> dict[str, Any]:
    """Return the parsed ``baked_manifest.json`` payload."""
    path = manifest_path or _MANIFEST_PATH
    return json.loads(path.read_text())


def verify_all(
    manifest_path: Path | None = None,
    data_dir: Path | None = None,
) -> None:
    """Verify every artifact in ``baked_manifest.json`` matches its
    recorded sha256.

    Raises:
        BakeManifestMismatch: if any artifact is missing or its digest
            disagrees with the recorded one.
    """
    manifest = load_manifest(manifest_path)
    directory = data_dir or _DATA_DIR
    for entry in manifest.get("artifacts", []):
        name = entry["name"]
        expected = entry["sha256"]
        path = directory / name
        if not path.exists():
            raise BakeManifestMismatch(
                f"baked asset missing: {name} not found at {path}"
            )
        actual = _sha256_file(path)
        if actual != expected:
            raise BakeManifestMismatch(
                f"baked asset digest drift: {name}\n"
                f"  expected: {expected}\n"
                f"  actual:   {actual}\n"
                "Re-run perception/data/generate_baked.py to refresh."
            )
