"""Coworld-compatible packaging artifacts for generated agents.

A Coworld player is a Docker image whose entrypoint reads
``COGAMES_ENGINE_WS_URL`` from the env, connects to the game websocket the
runner exposes, plays the episode, and exits. This module renders the
:file:`Dockerfile` and :file:`.dockerignore` that wrap a generated agent
into that shape.

The image still depends on the in-repo ``agent_policies`` framework, which
``agent/framework_bootstrap.py`` imports via absolute path. The generated
Dockerfile documents the two supported ways to supply the framework inside
the image (vendor the source, or pip-install a wheel) without choosing
between them — picking is an operator decision, not a generator one.
"""

from __future__ import annotations

from pathlib import Path

from .artifacts import write_text
from .framework import AgentFrameworkRef


COWORLD_DOCKERFILE_NAME = "Dockerfile"
COWORLD_DOCKERIGNORE_NAME = ".dockerignore"


def write_coworld_packaging(
    output_dir: Path,
    *,
    agent_framework: AgentFrameworkRef,
) -> tuple[Path, Path]:
    """Write a Coworld-compatible ``Dockerfile`` and ``.dockerignore`` at ``output_dir``.

    Returns the paths written so callers can include them in their manifests.
    """

    dockerfile_path = output_dir / COWORLD_DOCKERFILE_NAME
    dockerignore_path = output_dir / COWORLD_DOCKERIGNORE_NAME
    write_text(dockerfile_path, render_dockerfile(agent_framework))
    write_text(dockerignore_path, render_dockerignore())
    return dockerfile_path, dockerignore_path


def render_dockerfile(agent_framework: AgentFrameworkRef) -> str:
    return f"""# Generated by maker_v1. Builds a Coworld-compatible player image.
#
# Workflow (see https://github.com/Metta-AI/metta/tree/main/packages/coworld
# for the full CLI reference):
#
#   docker build --platform=linux/amd64 -t my-player:latest .
#   uv run coworld run-episode path/to/coworld_manifest.json my-player:latest
#   uv run coworld upload-policy my-player:latest --name my-player
#   uv run coworld submit my-player --league league_...
#
# The Coworld runner sets COGAMES_ENGINE_WS_URL in this container's env.
# The entrypoint connects to that websocket, plays the episode, and exits.

FROM python:3.12-slim

WORKDIR /app

# Runtime deps. The generated entrypoint speaks the binary websocket
# protocol defined by the game container's player protocol document.
RUN pip install --no-cache-dir websockets

# Bundle the generated agent code.
COPY agent/ /app/agent/

# The generated agent imports the Cyborg framework
# ({agent_framework.package}) via agent/framework_bootstrap.py, which records the
# framework source root at generation time (a host-absolute path).
#
# Choose ONE of the following to make the framework importable inside the
# image, then update agent/framework_bootstrap.py's PACKAGE_SOURCE_ROOT to
# match (or set PYTHONPATH so the import resolves):
#
# (A) Vendor the framework source into the image:
#     COPY ./vendor/agent_policies/ /app/agent_policies/
#     ENV PYTHONPATH=/app
#
# (B) Pip-install a published wheel (when one is available):
#     RUN pip install --no-cache-dir agent-policies==<pinned-version>
#
# Leaving this section unresolved produces an image whose entrypoint will
# raise at import time. Resolve it before `coworld upload-policy`.

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "/app/agent/run_agent.py"]
"""


def render_dockerignore() -> str:
    return """# Files that should never enter the player image.
**/__pycache__
**/*.pyc
**/*.pyo
**/.pytest_cache
**/.ruff_cache
**/.mypy_cache
.git
.gitignore
.venv
.env
.envrc

# maker_v1 outputs that aren't part of the runtime image.
visual_bootstrap/
smoke_tests/
maker_manifest.json
AGENT_BUILD_PLAN.md
README.md
"""
