from __future__ import annotations

import json
import pprint
import re
from pathlib import Path
from typing import Any

from .artifacts import write_json, write_text
from .guide_index import Evidence, GuideBundle, ObservationSurface


DECODER_SPEC_SCHEMA_VERSION = "maker.decoder_spec.v1"


def generate_decoder_artifacts(
    *,
    bundle: GuideBundle,
    output_dir: Path,
    surface: ObservationSurface,
) -> tuple[Path, ...]:
    spec = build_decoder_spec(bundle=bundle, surface=surface)
    spec_file = output_dir / "agent" / "perception" / "decoder_spec.json"
    task_file = output_dir / "agent" / "perception" / "DECODER_GENERATION_TASK.md"
    decoder_file = output_dir / "agent" / "perception" / "decoder.py"
    init_file = output_dir / "agent" / "perception" / "__init__.py"
    test_file = output_dir / "agent" / "tests" / f"test_{_test_module_prefix(bundle.game_slug, output_dir)}_decoder.py"
    _remove_generated_decoder_tests(output_dir / "agent" / "tests")
    write_json(spec_file, spec)
    write_text(task_file, render_decoder_generation_task(spec))
    write_text(init_file, _render_decoder_init())
    write_text(decoder_file, _render_decoder_impl(spec))
    write_text(test_file, _render_decoder_tests(spec))
    return (spec_file, task_file, init_file, decoder_file, test_file)


def build_decoder_spec(
    *,
    bundle: GuideBundle,
    surface: ObservationSurface,
) -> dict[str, Any]:
    evidence = _extract_decoder_evidence(bundle)
    contract_observation = _contract_observation(bundle)
    contract_evidence = _contract_decoder_evidence(contract_observation)
    evidence = _dedupe_evidence((*contract_evidence, *evidence))
    input_kind = _contract_input_kind(contract_observation) or _classify_decoder_input(surface, evidence)
    hints = _merge_contract_hints(_extract_decoder_hints(evidence), contract_observation)
    strategy = _decoder_strategy(surface, input_kind)
    needs_generated_decoder = strategy in {"generate_symbolic_decoder", "generate_visual_decoder"}
    vlm_ready_without_decoder = input_kind in {"encoded_image", "structured_symbolic"}

    return {
        "schema_version": DECODER_SPEC_SCHEMA_VERSION,
        "game_slug": bundle.game_slug,
        "guide_bundle_hash": bundle.bundle_hash,
        "observation_surface": surface.as_dict(),
        "input_kind": input_kind,
        "decoder_strategy": strategy,
        "needs_generated_decoder": needs_generated_decoder,
        "vlm_ready_without_decoder": vlm_ready_without_decoder,
        "source_documents": [
            "INTERFACE_CONTRACT.md",
            "OBSERVATION_DECODING.md",
            "STATE_AND_VIEW_MODEL.md",
            "MINIMUM_VIABLE_AGENT.md",
        ],
        "evidence": [item.as_dict() for item in evidence],
        "extracted_hints": hints,
        "output_contract": _output_contract(surface, input_kind),
        "implementation_requirements": _implementation_requirements(surface, input_kind),
        "validation_checks": _validation_checks(surface, input_kind),
        "generalization_rule": (
            "Decoder code must be generated from this game bundle's guide docs and source evidence. "
            "Do not reuse assumptions from another game's framebuffer, palette, dimensions, transport, "
            "or observation schema unless those assumptions are rediscovered for this game."
        ),
    }


def render_decoder_generation_task(spec: dict[str, Any]) -> str:
    evidence_lines = "\n".join(
        f"- `{item['document']}:{item['line']}`: {item['text']}" for item in spec["evidence"]
    ) or "- No decoder-specific evidence was found in the guide bundle."
    hints = spec["extracted_hints"]
    hint_lines = "\n".join(
        f"- {key}: {', '.join(str(value) for value in values) if values else 'none'}"
        for key, values in hints.items()
    )
    requirements = "\n".join(f"- {item}" for item in spec["implementation_requirements"])
    checks = "\n".join(f"- {item}" for item in spec["validation_checks"])

    return f"""# Decoder Generation Task

Generated by `maker_v1`.

This is a generated artifact. It describes what a game-specific observation
decoder must do before VLM labeling or parser generation can be reliable.

## Decoder Boundary

- Game: `{spec["game_slug"]}`
- Observation surface: `{spec["observation_surface"]["category"]}`
- Input kind: `{spec["input_kind"]}`
- Strategy: `{spec["decoder_strategy"]}`
- Needs generated decoder: `{spec["needs_generated_decoder"]}`
- VLM-ready without decoder: `{spec["vlm_ready_without_decoder"]}`

## Generalization Rule

{spec["generalization_rule"]}

## Source Evidence

{evidence_lines}

## Extracted Hints

{hint_lines}

## Output Contract

```json
{_jsonish(spec["output_contract"])}
```

## Implementation Requirements

{requirements}

## Validation Checks

{checks}

## Next Step

Use this task plus the guide bundle and game source to generate decoder code
under `agent/perception/`. If the guide evidence is incomplete, inspect the
source and update the generated guide or this decoder spec before writing code.
"""


def _extract_decoder_evidence(bundle: GuideBundle, *, limit: int = 20) -> tuple[Evidence, ...]:
    target_docs = (
        "INTERFACE_CONTRACT.md",
        "OBSERVATION_DECODING.md",
        "STATE_AND_VIEW_MODEL.md",
        "MINIMUM_VIABLE_AGENT.md",
    )
    evidence: list[Evidence] = []
    for filename in target_docs:
        document = bundle.get(filename)
        if document is None:
            continue
        for line_no, line in enumerate(document.content.splitlines(), start=1):
            cleaned = _clean_line(line)
            if not cleaned or _is_low_signal_line(cleaned):
                continue
            lowered = cleaned.lower()
            if any(pattern.search(lowered) for pattern in _DECODER_PATTERNS):
                evidence.append(Evidence(filename, line_no, cleaned))
                if len(evidence) >= limit:
                    return tuple(evidence)
    return tuple(evidence)


def _contract_observation(bundle: GuideBundle) -> dict[str, Any] | None:
    if bundle.contract is None:
        return None
    observation = bundle.contract.get("observation")
    return observation if isinstance(observation, dict) else None


def _contract_decoder_evidence(observation: dict[str, Any] | None) -> tuple[Evidence, ...]:
    if observation is None:
        return ()
    evidence_items: list[dict[str, Any]] = []
    primary = observation.get("primary")
    if isinstance(primary, dict):
        raw = primary.get("evidence")
        if isinstance(raw, list):
            evidence_items.extend(item for item in raw if isinstance(item, dict))
    raw = observation.get("evidence")
    if isinstance(raw, list):
        evidence_items.extend(item for item in raw if isinstance(item, dict))

    evidence: list[Evidence] = []
    for item in evidence_items:
        document = item.get("document")
        line = item.get("line")
        text = item.get("text")
        if not isinstance(document, str) or not isinstance(text, str):
            continue
        try:
            line_no = int(line)
        except (TypeError, ValueError):
            continue
        evidence.append(Evidence(document, line_no, text))
    return tuple(evidence[:20])


def _contract_input_kind(observation: dict[str, Any] | None) -> str | None:
    if observation is None:
        return None
    primary = observation.get("primary")
    if not isinstance(primary, dict):
        return None
    input_kind = primary.get("input_kind")
    if input_kind in {
        "structured_symbolic",
        "encoded_image",
        "raw_visual_observation",
        "mixed_visual_or_symbolic_unknown",
        "visual_unknown_encoding",
    }:
        return str(input_kind)
    return None


def _merge_contract_hints(
    hints: dict[str, list[str]],
    observation: dict[str, Any] | None,
) -> dict[str, list[str]]:
    if observation is None:
        return hints
    primary = observation.get("primary")
    if not isinstance(primary, dict):
        return hints
    merged = {key: list(value) for key, value in hints.items()}
    width = primary.get("width")
    height = primary.get("height")
    if isinstance(width, int) and isinstance(height, int):
        _append_unique(merged["dimensions"], f"{width}x{height}")
    byte_length = primary.get("byte_length")
    if isinstance(byte_length, int):
        _append_unique(merged["byte_lengths"], f"{byte_length} bytes")
    bit_depth = primary.get("bit_depth")
    if isinstance(bit_depth, int):
        _append_unique(merged["bit_depths"], f"{bit_depth}-bit")
    transport = primary.get("transport")
    if isinstance(transport, str):
        for term in transport.split("_"):
            _append_unique(merged["transport_terms"], term)
    encoding = primary.get("encoding")
    if isinstance(encoding, str):
        for term in encoding.split("_"):
            _append_unique(merged["codec_terms"], term)
    return merged


def _append_unique(values: list[str], value: str) -> None:
    if value and value not in values:
        values.append(value)


def _dedupe_evidence(items: tuple[Evidence, ...]) -> tuple[Evidence, ...]:
    seen: set[tuple[str, int, str]] = set()
    result: list[Evidence] = []
    for item in items:
        key = (item.document, item.line, item.text)
        if key in seen:
            continue
        seen.add(key)
        result.append(item)
    return tuple(result)


def _classify_decoder_input(surface: ObservationSurface, evidence: tuple[Evidence, ...]) -> str:
    text = "\n".join(item.text.lower() for item in evidence)
    if surface.category == "symbolic_primary":
        return "structured_symbolic"
    if _has_encoded_image_evidence(text) and not _has_raw_visual_evidence(text):
        return "encoded_image"
    if _has_raw_visual_evidence(text):
        return "raw_visual_observation"
    if surface.category == "mixed_or_alternate":
        return "mixed_visual_or_symbolic_unknown"
    if surface.category == "visual_primary":
        return "visual_unknown_encoding"
    return "unknown"


def _decoder_strategy(surface: ObservationSurface, input_kind: str) -> str:
    if input_kind == "structured_symbolic":
        return "generate_symbolic_decoder"
    if input_kind == "encoded_image":
        return "pass_through_encoded_image"
    if input_kind in {"raw_visual_observation", "visual_unknown_encoding", "mixed_visual_or_symbolic_unknown"}:
        return "generate_visual_decoder"
    if surface.category in {"visual_primary", "mixed_or_alternate"}:
        return "generate_visual_decoder"
    return "defer_until_observation_contract_is_known"


def _extract_decoder_hints(evidence: tuple[Evidence, ...]) -> dict[str, list[str]]:
    text = "\n".join(item.text for item in evidence)
    return {
        "dimensions": _unique(re.findall(r"\b\d{2,5}\s*[xX×]\s*\d{2,5}\b", text)),
        "byte_lengths": _unique(re.findall(r"\b\d[\d,]*\s+bytes?\b", text, flags=re.I)),
        "bit_depths": _unique(re.findall(r"\b\d+\s*[- ]?bit\b", text, flags=re.I)),
        "image_formats": _unique(re.findall(r"\b(?:png|jpeg|jpg|webp|gif)\b", text, flags=re.I)),
        "transport_terms": _unique(
            term
            for term in ("BinaryMessage", "binary", "JSON", "websocket", "token", "array")
            if re.search(rf"\b{re.escape(term)}\b", text, flags=re.I)
        ),
        "codec_terms": _unique(
            term
            for term in ("packed", "framebuffer", "frame buffer", "palette", "sprite", "render", "pixels")
            if re.search(rf"\b{re.escape(term)}\b", text, flags=re.I)
        ),
    }


def _output_contract(surface: ObservationSurface, input_kind: str) -> dict[str, object]:
    if input_kind == "structured_symbolic":
        return {
            "primary_output": "typed_symbolic_observation",
            "vlm_image_fixture": "not_required_for_baseline",
        }
    if input_kind == "encoded_image":
        return {
            "primary_output": "decoded_image_fixture",
            "vlm_image_fixture": "pass_through_original_image_after_format_validation",
            "accepted_image_formats": ["png", "jpeg", "gif", "webp"],
        }
    if surface.category in {"visual_primary", "mixed_or_alternate"}:
        return {
            "primary_output": "png_image_fixture",
            "vlm_image_fixture": "png_image_fixture",
            "metadata": [
                "source_observation_hash",
                "decoder_name",
                "decoder_version",
                "width",
                "height",
                "source_evidence",
            ],
        }
    return {
        "primary_output": "unknown_until_observation_contract_is_resolved",
    }


def _implementation_requirements(surface: ObservationSurface, input_kind: str) -> list[str]:
    if input_kind == "structured_symbolic":
        return [
            "Generate a typed parser for the structured observation fields.",
            "Reject malformed observations with explicit errors or safe fallback state.",
            "No visual VLM image fixture is required for the baseline agent path.",
        ]
    if input_kind == "encoded_image":
        return [
            "Validate that incoming bytes are a supported encoded image format.",
            "Persist the original image or a normalized PNG fixture with stable hashing.",
            "Do not apply framebuffer-specific unpacking unless the source proves it is needed.",
        ]
    if surface.category in {"visual_primary", "mixed_or_alternate"}:
        return [
            "Generate decoder code from the target game's guide docs and source, not from another game's protocol.",
            "Convert raw player observations into PNG fixtures before Bedrock or other image VLM labeling.",
            "Emit metadata that records source hash, output dimensions, decoder version, and source evidence.",
            "Add fixture tests for representative observations and edge cases from the game source.",
        ]
    return [
        "Inspect guide docs and source to resolve the observation contract before generating decoder code.",
    ]


def _validation_checks(surface: ObservationSurface, input_kind: str) -> list[str]:
    if input_kind == "structured_symbolic":
        return [
            "Unit tests cover required fields, optional fields, terminal observations, and malformed input.",
            "Policy smoke tests consume the typed observation without VLM calls.",
        ]
    if input_kind == "encoded_image":
        return [
            "Fixture tests verify supported image formats are accepted and unsupported bytes are rejected.",
            "VLM bootstrap receives image bytes without codec-specific mutation.",
        ]
    if surface.category in {"visual_primary", "mixed_or_alternate"}:
        return [
            "Fixture tests prove raw observations decode to deterministic image hashes.",
            "Decoded image dimensions match source-derived expectations when known.",
            "Bedrock or another image VLM accepts the decoded fixture format.",
            "Decoder failures are surfaced before spending VLM budget.",
        ]
    return [
        "No decoder code should be generated until the observation contract is known.",
    ]


def _has_raw_visual_evidence(text: str) -> bool:
    return any(pattern.search(text) for pattern in _RAW_VISUAL_PATTERNS)


def _has_encoded_image_evidence(text: str) -> bool:
    return any(pattern.search(text) for pattern in _ENCODED_IMAGE_PATTERNS)


def _unique(values: Any) -> list[str]:
    result: list[str] = []
    for value in values:
        normalized = str(value).strip()
        if not normalized or normalized in result:
            continue
        result.append(normalized)
    return result


def _render_decoder_init() -> str:
    return '''from __future__ import annotations

from .decoder import DecodeError, DecodedObservation, decode_observation, decode_to_vlm_image

__all__ = [
    "DecodeError",
    "DecodedObservation",
    "decode_observation",
    "decode_to_vlm_image",
]
'''


def _render_decoder_impl(spec: dict[str, Any]) -> str:
    input_kind = str(spec["input_kind"])
    strategy = str(spec["decoder_strategy"])
    hints = spec["extracted_hints"]
    width, height = _dimension_from_hints(hints)
    expected_bytes = _expected_bytes_from_hints(hints)
    bit_depth = _bit_depth_from_hints(hints)
    can_decode_packed_4bit = (
        input_kind == "raw_visual_observation"
        and width is not None
        and height is not None
        and expected_bytes is not None
        and bit_depth == 4
        and "packed" in hints.get("codec_terms", [])
    )
    spec_literal = pprint.pformat(spec, sort_dicts=True, width=100)
    return f'''from __future__ import annotations

import hashlib
import json
import struct
import zlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any


DECODER_NAME = "generated_{_test_module_prefix(str(spec["game_slug"]))}_decoder"
DECODER_VERSION = "maker.decoder_impl.v1"
DECODER_SPEC: dict[str, Any] = {spec_literal}
INPUT_KIND = {input_kind!r}
DECODER_STRATEGY = {strategy!r}
FRAME_WIDTH = {width!r}
FRAME_HEIGHT = {height!r}
EXPECTED_SOURCE_BYTES = {expected_bytes!r}
BIT_DEPTH = {bit_depth!r}
CAN_DECODE_PACKED_4BIT = {can_decode_packed_4bit!r}


class DecodeError(ValueError):
    pass


@dataclass(frozen=True, slots=True)
class DecodedObservation:
    image_bytes: bytes | None
    image_format: str | None
    symbolic: dict[str, Any] | None
    metadata: dict[str, Any]


def decode_observation(payload: bytes | str | dict[str, Any]) -> DecodedObservation:
    source_hash = _source_hash(payload)
    if INPUT_KIND == "structured_symbolic":
        symbolic = _decode_symbolic(payload)
        return DecodedObservation(
            image_bytes=None,
            image_format=None,
            symbolic=symbolic,
            metadata=_metadata(source_hash, primary_output="typed_symbolic_observation"),
        )

    if INPUT_KIND == "encoded_image":
        image_bytes = _coerce_bytes(payload)
        image_format = _detect_image_format(image_bytes)
        if image_format is None:
            raise DecodeError("Expected PNG, JPEG, GIF, or WebP image bytes.")
        return DecodedObservation(
            image_bytes=image_bytes,
            image_format=image_format,
            symbolic=None,
            metadata=_metadata(source_hash, primary_output="decoded_image_fixture"),
        )

    if CAN_DECODE_PACKED_4BIT:
        image_bytes = _decode_packed_4bit_to_png(_coerce_bytes(payload))
        return DecodedObservation(
            image_bytes=image_bytes,
            image_format="png",
            symbolic=None,
            metadata=_metadata(source_hash, primary_output="png_image_fixture"),
        )

    raise DecodeError(
        "This generated decoder does not have enough source-grounded evidence to decode "
        f"input_kind={{INPUT_KIND!r}} strategy={{DECODER_STRATEGY!r}}. Review decoder_spec.json "
        "and update the guide/source evidence before VLM labeling raw observations."
    )


def decode_to_vlm_image(payload: bytes | str | dict[str, Any]) -> tuple[bytes, str, dict[str, Any]]:
    decoded = decode_observation(payload)
    if decoded.image_bytes is None or decoded.image_format is None:
        raise DecodeError("Decoded observation does not produce a VLM image fixture.")
    return decoded.image_bytes, decoded.image_format, decoded.metadata


def write_decoded_fixture(payload: bytes | str | dict[str, Any], output_dir: Path) -> dict[str, Any]:
    image_bytes, image_format, metadata = decode_to_vlm_image(payload)
    output_dir.mkdir(parents=True, exist_ok=True)
    fixture_hash = hashlib.sha256(image_bytes).hexdigest()
    image_path = output_dir / f"{{fixture_hash}}.{{image_format}}"
    metadata_path = output_dir / f"{{fixture_hash}}.json"
    image_path.write_bytes(image_bytes)
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\\n", encoding="utf-8")
    return {{
        "image_path": str(image_path),
        "metadata_path": str(metadata_path),
        "image_hash": fixture_hash,
        "image_format": image_format,
        "metadata": metadata,
    }}


def _decode_symbolic(payload: bytes | str | dict[str, Any]) -> dict[str, Any]:
    if isinstance(payload, dict):
        return dict(payload)
    if isinstance(payload, bytes):
        payload = payload.decode("utf-8")
    if not isinstance(payload, str):
        raise DecodeError(f"Unsupported symbolic payload type: {{type(payload).__name__}}")
    parsed = json.loads(payload)
    if not isinstance(parsed, dict):
        raise DecodeError("Symbolic observation JSON must decode to an object.")
    return parsed


def _decode_packed_4bit_to_png(payload: bytes) -> bytes:
    if EXPECTED_SOURCE_BYTES is not None and len(payload) != EXPECTED_SOURCE_BYTES:
        raise DecodeError(f"Expected {{EXPECTED_SOURCE_BYTES}} source bytes, got {{len(payload)}}.")
    if FRAME_WIDTH is None or FRAME_HEIGHT is None:
        raise DecodeError("Packed visual decoder is missing frame dimensions.")
    expected_pixels = FRAME_WIDTH * FRAME_HEIGHT
    if len(payload) * 2 != expected_pixels:
        raise DecodeError(
            f"Packed 4-bit payload has {{len(payload) * 2}} pixels, expected {{expected_pixels}}."
        )
    pixels = bytearray()
    for value in payload:
        pixels.append(((value >> 4) & 0x0F) * 17)
        pixels.append((value & 0x0F) * 17)
    return _png_from_grayscale(bytes(pixels), FRAME_WIDTH, FRAME_HEIGHT)


def _png_from_grayscale(pixels: bytes, width: int, height: int) -> bytes:
    if len(pixels) != width * height:
        raise DecodeError("Pixel count does not match PNG dimensions.")
    rows = bytearray()
    for y in range(height):
        rows.append(0)
        start = y * width
        rows.extend(pixels[start : start + width])
    return (
        b"\\x89PNG\\r\\n\\x1a\\n"
        + _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0))
        + _png_chunk(b"IDAT", zlib.compress(bytes(rows)))
        + _png_chunk(b"IEND", b"")
    )


def _png_chunk(kind: bytes, data: bytes) -> bytes:
    import binascii

    checksum = binascii.crc32(kind)
    checksum = binascii.crc32(data, checksum) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", checksum)


def _coerce_bytes(payload: bytes | str | dict[str, Any]) -> bytes:
    if isinstance(payload, bytes):
        return payload
    if isinstance(payload, str):
        return payload.encode("utf-8")
    raise DecodeError(f"Expected bytes payload, got {{type(payload).__name__}}.")


def _detect_image_format(image_bytes: bytes) -> str | None:
    if image_bytes.startswith(b"\\x89PNG\\r\\n\\x1a\\n"):
        return "png"
    if image_bytes.startswith(b"\\xff\\xd8\\xff"):
        return "jpeg"
    if image_bytes.startswith((b"GIF87a", b"GIF89a")):
        return "gif"
    if len(image_bytes) >= 12 and image_bytes[:4] == b"RIFF" and image_bytes[8:12] == b"WEBP":
        return "webp"
    return None


def _metadata(source_hash: str, *, primary_output: str) -> dict[str, Any]:
    return {{
        "decoder_name": DECODER_NAME,
        "decoder_version": DECODER_VERSION,
        "decoder_strategy": DECODER_STRATEGY,
        "input_kind": INPUT_KIND,
        "primary_output": primary_output,
        "source_observation_hash": source_hash,
        "width": FRAME_WIDTH,
        "height": FRAME_HEIGHT,
        "source_evidence": DECODER_SPEC.get("evidence", []),
    }}


def _source_hash(payload: bytes | str | dict[str, Any]) -> str:
    if isinstance(payload, bytes):
        data = payload
    elif isinstance(payload, str):
        data = payload.encode("utf-8")
    else:
        data = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(data).hexdigest()
'''


def _render_decoder_tests(spec: dict[str, Any]) -> str:
    input_kind = str(spec["input_kind"])
    hints = spec["extracted_hints"]
    width, height = _dimension_from_hints(hints)
    expected_bytes = _expected_bytes_from_hints(hints)
    bit_depth = _bit_depth_from_hints(hints)
    can_decode_packed_4bit = (
        input_kind == "raw_visual_observation"
        and width is not None
        and height is not None
        and expected_bytes is not None
        and bit_depth == 4
        and "packed" in hints.get("codec_terms", [])
    )
    if input_kind == "structured_symbolic":
        body = '''def test_decode_symbolic_dict() -> None:
    decoded = decoder.decode_observation({"type": "observation", "tick": 1})
    assert decoded.symbolic["tick"] == 1
    assert decoded.image_bytes is None


def test_decode_symbolic_json_bytes() -> None:
    decoded = decoder.decode_observation(b'{"type":"observation","tick":2}')
    assert decoded.symbolic["tick"] == 2
'''
    elif input_kind == "encoded_image":
        body = '''def test_passes_through_png() -> None:
    decoded = decoder.decode_observation(_png_fixture())
    assert decoded.image_format == "png"
    assert decoded.image_bytes.startswith(b"\\x89PNG")


def test_rejects_non_image_bytes() -> None:
    try:
        decoder.decode_observation(b"not-image")
    except decoder.DecodeError:
        pass
    else:
        raise AssertionError("non-image bytes should be rejected")
'''
    elif can_decode_packed_4bit:
        body = f'''def test_decodes_packed_4bit_to_png() -> None:
    raw = bytes([0x0F]) * {expected_bytes}
    decoded = decoder.decode_observation(raw)
    assert decoded.image_format == "png"
    assert decoded.image_bytes.startswith(b"\\x89PNG")
    assert _png_size(decoded.image_bytes) == ({width}, {height})
    assert decoded.metadata["source_observation_hash"]


def test_rejects_wrong_payload_size() -> None:
    try:
        decoder.decode_observation(b"too-short")
    except decoder.DecodeError as exc:
        assert "Expected" in str(exc)
    else:
        raise AssertionError("wrong-size payload should be rejected")
'''
    else:
        body = '''def test_decoder_requires_more_evidence() -> None:
    try:
        decoder.decode_observation(b"raw")
    except decoder.DecodeError as exc:
        assert "not have enough source-grounded evidence" in str(exc)
    else:
        raise AssertionError("decoder should fail until evidence is sufficient")
'''
    return f'''from __future__ import annotations

import importlib.util
import struct
import sys
from pathlib import Path
from types import ModuleType


def _load_decoder() -> ModuleType:
    path = Path(__file__).resolve().parents[1] / "perception" / "decoder.py"
    spec = importlib.util.spec_from_file_location("_generated_decoder_" + Path(__file__).resolve().parents[2].name, path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


decoder = _load_decoder()


def _png_size(payload: bytes) -> tuple[int, int]:
    assert payload.startswith(b"\\x89PNG\\r\\n\\x1a\\n")
    return struct.unpack(">II", payload[16:24])


def _png_fixture() -> bytes:
    return (
        b"\\x89PNG\\r\\n\\x1a\\n"
        b"\\x00\\x00\\x00\\rIHDR"
        b"\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x01\\x08\\x00\\x00\\x00\\x00"
        b"\\x3a\\x7e\\x9b\\x55"
        b"\\x00\\x00\\x00\\x0aIDATx\\x9cc```\\x00\\x00\\x00\\x04\\x00\\x01"
        b"\\xf6\\x178U"
        b"\\x00\\x00\\x00\\x00IEND\\xaeB`\\x82"
    )


{body}'''


def _dimension_from_hints(hints: dict[str, list[str]]) -> tuple[int | None, int | None]:
    for raw in hints.get("dimensions", []):
        match = re.search(r"(\d{2,5})\s*[xX×]\s*(\d{2,5})", raw)
        if match is not None:
            return int(match.group(1)), int(match.group(2))
    return None, None


def _expected_bytes_from_hints(hints: dict[str, list[str]]) -> int | None:
    for raw in hints.get("byte_lengths", []):
        match = re.search(r"(\d[\d,]*)\s+bytes?", raw, flags=re.I)
        if match is not None:
            return int(match.group(1).replace(",", ""))
    return None


def _bit_depth_from_hints(hints: dict[str, list[str]]) -> int | None:
    for raw in hints.get("bit_depths", []):
        match = re.search(r"(\d+)\s*[- ]?bit", raw, flags=re.I)
        if match is not None:
            return int(match.group(1))
    return None


def _test_module_prefix(game_slug: str, output_dir: Path | None = None) -> str:
    slug = re.sub(r"[^0-9A-Za-z_]+", "_", game_slug).strip("_").lower() or "game"
    if output_dir is None:
        return slug
    output_name = re.sub(r"[^0-9A-Za-z_]+", "_", output_dir.name).strip("_").lower()
    if not output_name or output_name == slug:
        return slug
    return f"{slug}_{output_name}"


def _remove_generated_decoder_tests(test_dir: Path) -> None:
    for path in test_dir.glob("test_*_decoder.py"):
        if path.exists() and _looks_like_generated_decoder_test(path):
            path.unlink()


def _looks_like_generated_decoder_test(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    return 'Path(__file__).resolve().parents[1] / "perception" / "decoder.py"' in text


def _jsonish(payload: dict[str, object]) -> str:
    import json

    return json.dumps(payload, indent=2, sort_keys=True)


def _clean_line(line: str) -> str:
    return " ".join(line.strip().strip("|").split())


def _is_low_signal_line(line: str) -> bool:
    stripped = line.strip()
    return not stripped or stripped.startswith("#") or stripped.startswith("```") or set(stripped) <= {"|", "-", ":", " "}


_DECODER_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\b(binary|BinaryMessage|bytes?|payload|websocket)\b", re.I),
    re.compile(r"\b(frame ?buffer|framebuffer|pixels?|palette|packed|screenshot|image|png|jpeg|jpg|webp|gif)\b", re.I),
    re.compile(r"\b(render|sprite|token array|observation_shape|structured|json|fields?)\b", re.I),
    re.compile(r"\b\d{2,5}\s*[xX×]\s*\d{2,5}\b", re.I),
)

_RAW_VISUAL_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bpacked\b", re.I),
    re.compile(r"\bframe ?buffer\b|\bframebuffer\b", re.I),
    re.compile(r"\bbinary\b.*\b(frame|payload|message|observation)\b", re.I),
    re.compile(r"\braw\b.*\b(image|pixels?|bytes?)\b", re.I),
    re.compile(r"\bpalette\b|\bsprite\b|\brender packet\b", re.I),
)

_ENCODED_IMAGE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bpng\b|\bjpeg\b|\bjpg\b|\bwebp\b|\bgif\b", re.I),
    re.compile(r"\bscreenshot\b|\bencoded image\b", re.I),
)
