## Generates BRANCH_IDS.md by grepping all branch-fired call sites
## under the modulabot module.
##
## Run from the modulabot directory:
##   nim r tools/gen_branch_ids.nim
##
## Writes BRANCH_IDS.md alongside DESIGN.md and TRACING.md.

import std/[os, strutils, algorithm, sets, strformat]

const ModulabotDir = currentSourcePath().parentDir.parentDir

type Hit = object
  branchId: string
  filePath: string
  lineNumber: int
  line: string

proc scanFile(path: string, hits: var seq[Hit]) =
  ## Walk one source file looking for literal branch-fired calls.
  ## The bootstrap pattern is `bot.fired(` plus an opening double
  ## quote on the same line. Calls that build a branch ID from a
  ## variable are NOT detected — those branches need a literal call
  ## site to appear in the doc.
  let rel = path.relativePath(ModulabotDir)
  var lineNo = 0
  let needle = "bot.fired(\""
  for raw in lines(path):
    inc lineNo
    let trimmed = raw.strip()
    # Skip lines that are themselves declaring the search needle
    # (e.g. inside the generator). These are easy to spot because
    # they contain `let needle = "bot.fired`.
    if trimmed.contains("let needle ="):
      continue
    let pos = trimmed.find(needle)
    if pos < 0: continue
    let after = trimmed[pos + needle.len .. ^1]
    let endQuote = after.find("\"")
    if endQuote < 0: continue
    let branchId = after[0 ..< endQuote]
    if branchId.len == 0: continue
    hits.add(Hit(
      branchId:    branchId,
      filePath:    rel,
      lineNumber:  lineNo,
      line:        trimmed
    ))

proc walkSources(): seq[Hit] =
  result = @[]
  for path in walkDirRec(ModulabotDir):
    if path.endsWith(".nim") and not path.contains("nimcache"):
      scanFile(path, result)

proc render(hits: seq[Hit]): string =
  var sortedHits = hits
  sortedHits.sort(proc (a, b: Hit): int =
    cmp(a.branchId, b.branchId))
  var seen = initHashSet[string]()
  var lines: seq[string] = @[]
  lines.add("# Branch IDs (auto-generated)")
  lines.add("")
  lines.add("Generated by `tools/gen_branch_ids.nim`. Run after editing")
  lines.add("any `bot.fired(...)` site. Cross-references TRACING.md §8.2.")
  lines.add("")
  lines.add("| Branch ID | Source |")
  lines.add("|---|---|")
  for h in sortedHits:
    if h.branchId in seen: continue
    seen.incl(h.branchId)
    lines.add(&"| `{h.branchId}` | `{h.filePath}:{h.lineNumber}` |")
  lines.add("")
  lines.add(&"_Total distinct branch IDs: {seen.len}_")
  result = lines.join("\n") & "\n"

proc main() =
  let hits = walkSources()
  let outPath = ModulabotDir / "BRANCH_IDS.md"
  writeFile(outPath, render(hits))
  echo &"wrote {outPath} with {hits.len} call site(s)"

when isMainModule:
  main()
